### ISSUE TITLE
development run always deletes database

### ISSUE THREAD

**Issue by yohny** [ERNICommunity/ERNI-Photo-Database#19]
When running in dev mode we always call `context.Database.EnsureDeleted();` which drops the database. Whats the motivation behind this? it would be nice to be able to develop with persistance between sessions :smile:

**Comment by mareklinka** [comment]
Yeah, the idea here was that to avoid having to introduce EF migrations early, we will just drop/recreate in the early stages (where model fluctuations). We could get rid of the `EnsureDeleted` call and either introduce migrations or just drop and recreate manually as needed.

**Comment by menyet** [comment]
#32
