### ISSUE TITLE
model naming conventions

### ISSUE THREAD

**Issue by yohny** [ERNICommunity/ERNI-Photo-Database#20]
we should stick to EF naming conventions in model:
* use plural for table names https://github.com/ERNICommunity/ERNI-Photo-Database/blob/9ba85f11c6720341eeeb3e1023421530bc956b5a/server/ERNI.PhotoDatabase.DataAccess/EntityConfiguration/TagConfiguration.cs#L11
* use plural for collection navigation properties https://github.com/ERNICommunity/ERNI-Photo-Database/blob/9ba85f11c6720341eeeb3e1023421530bc956b5a/server/ERNI.PhotoDatabase.DataAccess/DomainModel/Photo.cs#L16

**Comment by mareklinka** [comment]
Agreed.
