### ISSUE TITLE
Connection string in config

### ISSUE THREAD

**Issue by yohny** [ERNICommunity/ERNI-Photo-Database#34]
We used to have db connection string stored using user secrets (README still says we do), but in current implementation it is read from config.
Is it a temporary solution/workaround? Whats the story behind the change?

**Comment by menyet** [comment]
You can still store then in the app secrets. The pull request #29 just changed the format of how we store them, so we can override them in azure configuration.

**Comment by yohny** [comment]
well now the connection string is retrieved using `Configuration.GetConnectionString("Database")` [here](https://github.com/ERNICommunity/ERNI-Photo-Database/blob/74377f7c3dff6a1220b1b227a3403e48d6eae202/server/ERNI.PhotoDatabase.Server/Startup.cs#L51). I have the user secret called 'Database' set-up, but I get `NullReferenceException` from `.UseSqlServer()` extension method for connection string parameter, which means that it does not read user secrets currently.
If I add `Database` key to connections strings in appsettings.json (or appsettings.Development.json) it is read correctly, so it looks like that `Configuration.GetConnectionString()` only reads config files, but not user secrets.
I believe that if you would use user secrets as we had before using `Configuration.GetValue<string>("Database")` you can override in azure using environment variable with given name.

**Comment by menyet** [comment]
did you set the secret using the following format?
```
{
  "ConnectionStrings": {
    "Database": "Server=.\\SQLEXPRESS;Database=myDatabase;Trusted_Connection=True"
  }
}
```

**Comment by yohny** [comment]
eventually yes and it works. Now Im only missing oauth ClientId
